### ISSUE TITLE
Warning: Trying to access array offset on value of type int in src/LoremIpsum.php on line 355

### ISSUE THREAD

**Issue by tillkruss** [joshtronic/php-loremipsum#12]
I'm getting this warning:

```
Warning: Trying to access array offset on value of type int in vendor/joshtronic/php-loremipsum/src/LoremIpsum.php on line 355
```

**Comment by joshtronic** [comment]
Hey @tillkruss happen to have any additional details? The version of PHP you're using would be helpful

Thanks!

**Comment by tillkruss** [comment]
PHP 8.1

**Comment by joshtronic** [comment]
Quite peculiar. I went ahead and added PHP 8.1 to the test suite and the tests passed just fine, so I'm thinking it's possible related to however you're calling the code.

Can you pass along the code you're running that's resulting in the warning?

The code on the line referenced is expecting a string and is using array syntax against it (which is still value in 8.1). My thought is that perhaps you're passing in something that's not a string and that's causing the issue.

I can definitely stand to code a bit more defensively since it's not throwing a warning if the variable isn't the correct type.

**Comment by joshtronic** [comment]
Suspect the new release I just published will resolve this for you:
https://github.com/joshtronic/php-loremipsum/releases/tag/2.0.0

Cheers!

**Comment by tillkruss** [comment]
Thanks @joshtronic!

This is the related project btw: https://github.com/tillkruss/alfred-lorem-ipsum
