### ISSUE TITLE
Generate random date and time outputs

### ISSUE THREAD

**Issue by fernandoluiswendt** [joshtronic/php-loremipsum#5]
A little bit request issue for your very practical code: it would be interesting a feature to give a random date and time text characters output. As i am using Lorem to generate PDF print templates, that kind of stuff sounds good.

Something like this ones:

`//default date`
`$lipsum->date();`

`//date with layout specs`
`$lipsum->date("YYYY-MM-DD");`

`//default time`
`$lipsum->time();`

`//time with layout specs`
`$lipsum->time("H:M:S - TMZ");`
`
Only sugestions, to think about and consider, if you agree.

Best regards @joshtronic,

**Comment by joshtronic** [comment]
@fernandoluiswendt thanks for dropping me a note, that's definitely not something I had thought of (I mean, specifically because thus far it's been 100% lorem ipsum focused and dates don't necessarily fall into that category).

While falling somewhat outside of the original intention of this library, definitely will leave this open to see if it gets any additional up votes from the community and if so, really shouldn't take much to implement in the current 1.x branch of the library.

May actually spin up a separate lib for this tonight, since it's kind of a fun problem to solve :)

**Comment by joshtronic** [comment]
@fernandoluiswendt still trying to get travis to pick it up, but here's a new lib for ya -- https://github.com/joshtronic/php-randomdate

Since it's compatible with PHP's date in terms of the format, you should be able to get just about anything you want out of it.

Cheers!
